apiVersion: batch/v1
kind: CronJob
metadata:
  name: crm-worker
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: crm-worker
              image: hcdouat/improved-doodle:1.0.0-rc.1
              command:
                - /bin/sh
                - -c
                - . ~/.venv/bin/activate && python -m script
              env:
                - name: PGHOST
                  value: db
                - name: PGUSER
                  value: postgres
                - name: PGDATABASE
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: secret
                      key: POSTGRES_PASSWORD
                - name: CRM_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: secret
                      key: CRM_CLIENT_ID
                - name: CRM_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: secret
                      key: CRM_CLIENT_SECRET
          restartPolicy: Never
