apiVersion: v1
kind: Secret
metadata:
  name: secret
stringData:
  POSTGRES_PASSWORD: example
  CRM_CLIENT_ID: example
  CRM_CLIENT_SECRET: example
  OAUTH2_PROXY_CLIENT_ID: example
  OAUTH2_PROXY_CLIENT_SECRET: example
  OAUTH2_PROXY_COOKIE_SECRET: example
