name: Integration
on:
  push:
    branches:
      - "**"
jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    steps:
      - uses: actions/checkout@v6
      - run: curl -sfL https://get.k3s.io | sh -
      - run: kubectl wait node --for=condition=Ready --all --timeout=60s
      - run: kubectl apply -f k8s/
      - run: kubectl rollout status statefulset/db --timeout=120s
